"""Initial Migration

Revision ID: 3447fa6ebe3e
Revises: 
Create Date: 2022-08-02 19:38:33.490586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3447fa6ebe3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sender')
    op.drop_table('Receiver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Receiver',
    sa.Column('customerID', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False),
    sa.Column('recvStatus', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('customerID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Sender',
    sa.Column('customerID', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=60), nullable=False),
    sa.Column('dispatchStatus', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('customerID'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
